### ISSUE TITLE
Base bot

### ISSUE THREAD

**Issue by UsrBinLuna** [MaoZedong-Bot/Mao#1]
wip

**Comment by UsrBinLuna** [comment]
@SanderLippa what library do we use for this

**Comment by warp32767** [comment]
i love discord js discord js discord js

**Comment by UsrBinLuna** [comment]
it works i guess
missing some events

**Comment by UsrBinLuna** [comment]
i mean yeah its pretty much working i think. will reopen if any issues arise

**Comment by UsrBinLuna** [comment]
so yeah this is being reopened since were missing many event handlers
